version: '3.5'

services:
  teste-confiabilidade:
    image: teste-calculo-node
    expose:
      - "8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 1024M
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - teste-confiabilidade
    ports:
      - "4000:4000"
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4096M
        reservations:
          cpus: '3'
          memory: 4096M
